---
# Implement your Workload removal tasks here
- name: Ensure directory exists
  file:
    path: "{{ tmp_dir }}"
    state: directory

- name: Copy .kube/config and set env var
  copy:
    src: ~/.kube
    dest: "{{ tmp_dir }}"
    remote_src: true

- environment:
    KUBECONFIG: "{{ tmp_kubeconfig }}"
  block:
  - name: Remove project
    kubernetes.core.k8s_info:
      kind: Namespace
      name: "{{ aws_instance_retag_namespace }}"
      state: absent

- name: Remove temp kube config
  file:
    path: "{{ tmp_dir }}"
    state: absent

# Leave this as the last task in the playbook.
- name: remove_workload tasks complete
  debug:
    msg: "Remove Workload tasks completed successfully."
  when: not silent | bool
